### ISSUE TITLE
Firebase connection

### ISSUE THREAD

**Issue by pvaz** [5ebs/LinkedIn-Clone#1]
Hi,

trying to test you development and using my own firebase database, but not working.
Do you have any step by step guide on how to setup the firebase ?
Is it possible to use a local database for testing ?

Thanks,
Paulo

**Comment by 5ebs** [comment]
Hey Paulo,

I wrote a four-part series, where I show you how to build this LinkedIn Clone from scratch. This is the link https://javascript.plainenglish.io/how-to-build-a-linkedin-clone-683e392ee406

Here you can find the deployment to Firebase.
https://javascript.plainenglish.io/building-a-linkedin-clone-302206776137

I hope it can help you,
Gianmarco

**Comment by pvaz** [comment]
Hi Gianmarco,
thank you for your quick reply.
I'll look at it, surely will help to be able to test it.

Paulo

**Comment by pvaz** [comment]
Hi Gianmarco,

worked like a charm.
Do you have the clone in more advanced stage or plans to do it ?

Paulo
